# Generated by Django 6.0 on 2025-12-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transport_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.CharField(verbose_name='Цена'),
        ),
    ]
