# Generated by Django 6.0 on 2025-12-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
